name: Container job sample 
on:
  push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run a one-line script
              run: echo Hello, world!
            - name: Use Sample Action
              uses: ku1987/github-actions-apps-token@main
